/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Login.*;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NewUser extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps, pst = null;
    ResultSet rs = null;

    public NewUser() {
        initComponents();
        this.setTitle("New Uer signup");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signup = new javax.swing.JButton();
        pass1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        user1 = new javax.swing.JLabel();
        login_lable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        pass2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        tc = new javax.swing.JCheckBox();
        dob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        pass4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/images/bid.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Online Bidding Hub");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 780));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup.setBackground(new java.awt.Color(153, 0, 255));
        signup.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("sign up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 290, 50));

        pass1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pass1.setForeground(new java.awt.Color(51, 51, 51));
        pass1.setText("Password");
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        uname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, 30));

        user1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        user1.setForeground(new java.awt.Color(51, 51, 51));
        user1.setText("Username");
        jPanel2.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        login_lable.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        login_lable.setText("Sign up");
        jPanel2.add(login_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 30));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 20, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/images/menu1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 0, 58, 27));

        user2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        user2.setForeground(new java.awt.Color(51, 51, 51));
        user2.setText("Full Name");
        jPanel2.add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        fname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 290, 30));

        pass2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pass2.setForeground(new java.awt.Color(51, 51, 51));
        pass2.setText("Date of Birth");
        jPanel2.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        pass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 290, 30));

        tc.setBackground(new java.awt.Color(255, 255, 255));
        tc.setForeground(new java.awt.Color(51, 51, 51));
        tc.setText("I accept Terms and condition");
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        jPanel2.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        dob.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 290, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Already have an account? Login");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 730, -1, -1));

        city.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 290, 30));

        pass4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pass4.setForeground(new java.awt.Color(51, 51, 51));
        pass4.setText("City");
        jPanel2.add(pass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 380, 780));

        setSize(new java.awt.Dimension(848, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        String add = "INSERT INTO `login_info`(`Username`, `Password`, `UserType`) VALUES (?, ?, ?)";
        String sql = "INSERT INTO `customer_info`(`FullName`, `Username`, `Password`, `City`, `DOB`) VALUES (?,?,?,?,?)";
        con = SqlConnect.ConnectDB();
        if (tc.isSelected()) {

            try {

                ps = con.prepareStatement(sql);
                ps.setString(1, fname.getText());
                ps.setString(2, uname.getText());
                ps.setString(3, pass.getText());
                ps.setString(4, dob.getText());
                ps.setString(5, city.getText());

                ps.execute();

                pst = con.prepareStatement(add);
                pst.setString(1, uname.getText());
                pst.setString(2, pass.getText());
                pst.setString(3, "User");
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "New User Added successfully");

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please check the Terms & Conditions.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_signupActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(NewUser.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        loginArea login = new loginArea();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel login_lable;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JLabel pass2;
    private javax.swing.JLabel pass4;
    private javax.swing.JButton signup;
    private javax.swing.JCheckBox tc;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    // End of variables declaration//GEN-END:variables
}
